addSbtPlugin("com.eed3si9n"    % "sbt-assembly"    % "2.3.1")
addSbtPlugin("com.eed3si9n"    % "sbt-buildinfo"   % "0.13.1")
addSbtPlugin("org.scalameta"   % "sbt-scalafmt"    % "2.5.4")
addSbtPlugin("ch.epfl.scala"   % "sbt-scalafix"    % "0.14.0")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "3.3.0")
