name: CI -> check project build

on:
  pull_request:
    branches:
      - dev

jobs:
 check-build:
   if: ${{!contains(github.event.pull_request.labels.*.name, 'deploy_to_dev')}}
   uses: allaria-tech/infra-github-actions/.github/workflows/deploy-ecs.yml@main
   with:
    environment: development
    dry-run: true
    runs-on: self-hosted
   secrets: inherit
 scalafmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Scalafmt
        run: |
          VERSION=3.0.0
          INSTALL_LOCATION=/usr/local/bin/scalafmt-native
          curl https://raw.githubusercontent.com/scalameta/scalafmt/master/bin/install-scalafmt-native.sh | \
          sudo bash -s -- $VERSION $INSTALL_LOCATION
          scalafmt-native --help
      - name: Run Scalafmt and capture output
        id: scala_fmt_output
        run: scalafmt-native --config .scalafmt.conf --test