name: Development => Deploy from PR

on:
  pull_request:
    branches:
      - dev
    types:
      - labeled
      - synchronize
jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'deploy_to_dev')
    uses: allaria-tech/infra-github-actions/.github/workflows/deploy-ecs.yml@main
    with:
      environment: development
      runs-on: self-hosted
    secrets: inherit
    