name: Tag on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.70.0
        env:
          WITH_V: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

